// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherMonitor.Data;

namespace WeatherMonitor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200131114038_Add_Wind_Column")]
    partial class Add_Wind_Column
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WeatherMonitor.Entities.WeatherForecastEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("CityName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Humidity")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Pressure")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Temperature")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("WeatherCondition")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("WeatherConditionDetails")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("WeatherConditionIcon")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("WindSpeed")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");
                });
#pragma warning restore 612, 618
        }
    }
}
